### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by dalb8** [shagr4th/FrodoC64#1]
Is there a licence for this code and does it need a c64 binary to work? I am considering to distribute it via f-droid.org repository libre android apps. Btw we already had droid48 for a couple of days 6 months ago but it was pulled because of the restrictions on use of the ROM.

**Comment by shagr4th** [comment]
The original app is GPL, so this one is the same...
Not sure about the original rom bits though, but I' m sure there no problem
licence wise

**Comment by dalb8** [comment]
We have metadata for an app at http://jme64.sourceforge.net but we can't publish it due to field-of-use restrictions of the ROM binary.

**Comment by shagr4th** [comment]
yes you're right it seems the original rom is copyrighted by whatever
company bought the remains of Commodore... guess it's a showstopper :p
